development:
  adapter: postgresql
  encoding: unicode
#  database: <%= ENV['POSTGRES_DB'] %>
  database: ticket_app_development
  host: localhost
#  username: <%= ENV['POSTGRES_USER'] %>
#  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: ticketapp
  password: ticketapp1103
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
#  database: <%= ENV['POSTGRES_DB'] %>
  database: ticket_app_test
  host: localhost
#  username: <%= ENV['POSTGRES_USER'] %>
#  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: ticketapp
  password: ticketapp1103
  pool: 5
  timeout: 5000

host: localhost